UI/Pages/Index.cshtml.cs
using System.Security.Cryptography;
using System.Text;
using DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DB.Models;
using Microsoft.EntityFrameworkCore;

namespace UI.Pages;

public class IndexModel : PageModel
{
    private readonly ProjectContext Context;
    public const string SessionKeySecret = "_LoggedIn";
    [BindProperty] public List<Status> IndexList { get; set; }
    [BindProperty] public string PassString { get; set; }
    public Dictionary<string,Dictionary<char, List<Project>>>titleDictionary { get; set; }
    public IndexModel(ProjectContext context)
    {
        Context = context;
    }

    public async Task<IActionResult> OnGetAsync()
    {
        titleDictionary = new();
        IndexList = await Context.Statuses
            .AsNoTracking()
            .Include(s=>s.Projects)
                .ThenInclude(p=>p.Company)
            .Include(s=>s.Projects)
                .ThenInclude(p=>p.Consultants)
            .Include(s=>s.Projects)
                .ThenInclude(p=>p.Skills)
            .Where(s=>s.Name == "To Do" || s.Name == "Doing")
            .ToListAsync();
        foreach (var s in IndexList)
        {
            foreach (var p in s.Projects)
            {
                if (!titleDictionary.Keys.Contains(s.Name))
                {
                    titleDictionary[s.Name] = new();
                    if (!titleDictionary[s.Name].Keys.Contains(p.Name.ToLower()[0]))
                    {
                        titleDictionary[s.Name][p.Name.ToLower()[0]] = new();
                        titleDictionary[s.Name][p.Name.ToLower()[0]].Add(p);
                    }
                    else titleDictionary[s.Name][p.Name.ToLower()[0]].Add(p);
                }
                else
                {
                    if (!titleDictionary[s.Name].Keys.Contains(p.Name.ToLower()[0]))
                    {
                        titleDictionary[s.Name][p.Name.ToLower()[0]] = new();
                        titleDictionary[s.Name][p.Name.ToLower()[0]].Add(p);
                    }
                    else titleDictionary[s.Name][p.Name.ToLower()[0]].Add(p);
                }
            }
        }
        return Page();
    }

    public IActionResult OnGetSaveData()
    {
        if (string.IsNullOrEmpty(HttpContext.Session.GetString("_LoggedIn")))
        {
            return Redirect("/Index");
        }
        var content = Context.Companies
            .Include(c => c.Projects)
            .Include(c => c.Projects)
                .ThenInclude(p => p.Consultants)
            .Include(p => p.Projects)
                .ThenInclude(p => p.Skills);
        string name = "text.txt";
        FileInfo info = new FileInfo(name);
        using (StreamWriter sb = info.CreateText())
        {
            foreach (Company c in content)
            {
                sb.WriteLine("Company: " + c.Name);
                foreach (Project p in c.Projects)
                {
                    sb.WriteLine("Project: " + p.Name);
                    sb.WriteLine("Requested Skills:");
                    foreach (Skill s in p.Skills)
                    {
                        sb.WriteLine("\t" + s.Name);
                    }
                    sb.WriteLine("Consultants in project:");
                    for(int i = 0; i < p.Consultants.Count; i++)
                    {  
                        sb.WriteLine("\t" + (i+1) + ". "+ p.Consultants.ToList()[i].FullName);
                    }
                    sb.WriteLine();
                }
            }
        }
        return File(info.OpenRead(), "application/octet-stream", name);
    }
    public IActionResult OnPost()
    {
        string? passData = Request.Form["pass"].ToString();
        if (string.IsNullOrEmpty(passData)) return Redirect("/Index");
        var sb = new StringBuilder();
        var enc = Encoding.UTF8;
        using (var hash = SHA256.Create())
        {
            var result = hash.ComputeHash(enc.GetBytes(passData));
            foreach (var b in result)
                sb.Append(b.ToString("x2"));
        }
        if (sb.Equals("4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2".AsSpan()))
        {
            HttpContext.Session.SetString(SessionKeySecret, "yes");
        }
        return Redirect("/Index");
    }
}

UI/Pages/Shared/_Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">UI</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="btn-group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown">Admin</button>
                <div class="dropdown-menu">
                    <div class="dropdown-header">Consultants</div>
                    <a asp-page="/Consultants/Create" class="dropdown-item">Create</a>
                    <a asp-page="/Consultants/Index" class="dropdown-item">List All</a>
                    <div class="dropdown-header">Projects</div>
                    <a asp-page="/Projects/Create" class="dropdown-item">Create</a>
                    <a asp-page="/Projects/Index" class="dropdown-item">List All</a>
                    <div class="dropdown-header">Company</div>
                    <a asp-page="/Companies/Create" class="dropdown-item">Create</a>
                    <a asp-page="/Companies/Index" class="dropdown-item">List All</a>
                    <div class="dropdown-header">Other</div>
                    <a asp-page="/Index" asp-page-handler="SaveData" class="dropdown-item">Save Projects as Textfile</a>
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main">
    <div class="container p-4">
        @RenderBody()
    </div>
</main>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true"/>
</head>
<body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
                <div class="container"><a class="navbar-brand" asp-area="" asp-page="/Index">UI</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#adminModal" data-bs-whatever="admin">Admin</button>
                </div>
            </nav>
        </header>
    <main role="main">
        <div class="container">
        @RenderBody()
        </div>
        <div class="modal fade" id="adminModal" tabindex="-1" role="dialog" aria-labelledby="adminModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                <form method="post">
                  <div class="modal-header">
                      <h5 class="modal-title m-auto" id="adminModalLabel">Logga In</h5>
                  </div>
                  <div class="modal-body">
                      <label for="pass" class="col-form-label">Lösenord</label>
                      <input type="password"  class="form-control p-2 fs-5" id="pass" name="pass"/>
                  </div>
                      <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary">Logga In</button>
                      </div>
                </form>
              </div>
          </div>
        </div>
    </main>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>