UI/Pages/Companies/Create.cshtml.cs
using DB;
using DB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Company = DB.Models.Company;

namespace UI.Pages.Companies;

public class Create : PageModel
{
    private ProjectContext Context { get; set; }
    [BindProperty] public Company Company { get; set; }

    public Create(ProjectContext context)
    {
        Context = context;
    }

    public IActionResult OnGet()
    {
        if (string.IsNullOrEmpty(HttpContext.Session.GetString("_LoggedIn")))
        {
            return Redirect("/Index");
        } 
        return Page();
    }

    public IActionResult OnPost()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }
        if (null != Company) { 
            Context.Companies.Add(Company);
            Context.SaveChanges();
        }
        return Redirect("/Companies");
    }
}

UI/Pages/Companies/Delete.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DB;
using DB.Models;

namespace UI.Pages.Companies
{
    public class DeleteModel : PageModel
    {
        private readonly DB.ProjectContext _context;

        public DeleteModel(DB.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Company Company { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company = await _context.Companies.FirstOrDefaultAsync(m => m.Id == id);

            if (Company == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company = await _context.Companies.FindAsync(id);

            if (Company != null)
            {
                _context.Companies.Remove(Company);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

UI/Pages/Companies/Edit.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DB;
using DB.Models;

namespace UI.Pages.Companies
{
    public class EditModel : PageModel
    {
        private readonly DB.ProjectContext Context;

        public EditModel(DB.ProjectContext context)
        {
            Context = context;
        }

        [BindProperty]
        public Company Company { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company = await Context.Companies.FirstOrDefaultAsync(m => m.Id == id);

            if (Company == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Context.Attach(Company).State = EntityState.Modified;

            try
            {
                await Context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CompanyExists(Company.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CompanyExists(int id)
        {
            return Context.Companies.Any(e => e.Id == id);
        }
    }
}

UI/Pages/Consultants/Connect.cshtml.cs
using DB;
using DB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace UI.Pages.Consultants
{
    public class ConnectModel : PageModel
    {
        private ProjectContext Context { get; set; }
        [BindProperty]public Project PageProject { get; set; }
        public List<Consultant> ToRemove { get; set; }
        public List<Consultant> ToAdd { get; set; }
        public SelectList AddSelect { get; set; }
        public SelectList RemoveSelect { get; set; }
        [BindProperty] public Consultant ListConsult { get; set; }
        public ConnectModel(ProjectContext context)
        {
            Context = context;
        }
        public IActionResult OnGet(int? id)
        {
            if (!id.HasValue) {
                return Redirect("/Companies/Index");
            }
            PageProject = Context.Projects
                .Include(p => p.Consultants).Single(p=> p.Id == id);
            var projectConsultants = PageProject.Consultants.ToList();
            var allConsultants = Context.Consultants.ToList();
            ToAdd = allConsultants.Except(projectConsultants).ToList();
            RemoveSelect = new SelectList(projectConsultants, "Id", "FullName");
            AddSelect = new SelectList(ToAdd, "Id", "FullName");
            return Page();
        }

        public IActionResult OnPostAdd()
        {
            Project dbProject = Context.Projects.Single(p => p.Id == PageProject.Id);
            Consultant c = Context.Consultants.Single(c => c.Id == ListConsult.Id);
            Context.Entry(dbProject).Collection(c => c.Consultants).Load();
            dbProject.Consultants.Add(c);
            Context.Update(dbProject);
            Context.SaveChanges();
            return RedirectToPage("/Consultants/Connect", new{id=@PageProject.Id});
        }
        
        public IActionResult OnPostRemove()
        {
            PageProject = Context.Projects.Single(p => p.Id == PageProject.Id);
            ListConsult = Context.Consultants.Single(c => c.Id == ListConsult.Id);
            Context.Entry(PageProject).Collection(c => c.Consultants).Load();
            PageProject.Consultants.Remove(ListConsult);
            Context.Update(PageProject);
            Context.SaveChanges();
            return RedirectToPage("/Consultants/Connect", new{id=@PageProject.Id});
        }
    }
}

UI/Pages/Consultants/Create.cshtml.cs
using DB;
using DB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace UI.Pages.Consultants;

public class Create : PageModel
{
    private ProjectContext Context { get; set; }
    [BindProperty] public Consultant Consult { get; set; }
    public Create(ProjectContext context)
    {
        Context = context;
    }
    
    public IActionResult OnGet()
    {
        
        return Page();
    }

    public IActionResult OnPost()
    {
        if (string.IsNullOrEmpty(HttpContext.Session.GetString("_LoggedIn")))
        {
            return Redirect("/Index");
        }
        if (!ModelState.IsValid)
        {
            ViewData["ErrorMessage"] = "You missed filling in some details. Please try again";
            return Page();
        }
        Context.Consultants.Add(Consult);
        Context.SaveChanges();
        return Redirect("/Consultants/Index");
    }
}

UI/Pages/Consultants/Delete.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DB;
using DB.Models;

namespace UI.Pages.Consultants
{
    public class DeleteModel : PageModel
    {
        private readonly DB.ProjectContext _context;

        public DeleteModel(DB.ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Consultant Consultant { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Consultant = await _context.Consultants.FirstOrDefaultAsync(m => m.Id == id);

            if (Consultant == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Consultant = await _context.Consultants.FindAsync(id);

            if (Consultant != null)
            {
                _context.Consultants.Remove(Consultant);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

UI/Pages/Consultants/Edit.cshtml.cs
using DB;
using DB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;

namespace UI.Pages.Consultants
{
    public class EditModel : PageModel
    {
        private ProjectContext Context;
        [BindProperty] public Consultant ListConsultant { get; set; }
        public string SkillInput { get; set; }
        [BindProperty] public int SkillId { get; set; }
        public SelectList SkillSelect { get; set; }
        
        public EditModel(ProjectContext context)
        {
            Context = context;
        }

        public IActionResult OnGet(int? id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("_LoggedIn")))
            {
                return Redirect("/Index");
            }
            if (id == null)
            {
                return NotFound();
            }

            ListConsultant = Context.Consultants.Include(c=>c.Skills).SingleOrDefault(c => c.Id == id.Value);
            var consultSkills = ListConsultant.Skills.ToList();
            var allSkills = Context.Skills.ToList();
            List<Skill> remainingSkills = allSkills.Except(consultSkills).ToList();
            SkillSelect = new SelectList(remainingSkills, "Id", "Name");

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Context.Update(ListConsultant);
            Context.SaveChanges();
            return RedirectToPage("/Consultants/Index");
        }

    }
}

UI/Pages/Consultants/Index.cshtml.cs
using DB;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace UI.Pages.Consultants;

public class Index : PageModel
{
    private ProjectContext Context { get; set; }
    public List<Consultant> IndexList { get; set; }
    public List<Status> StatusList { get; set; }

    public Index(ProjectContext context)
    {
        Context = context;
    }
    public async Task<IActionResult> OnGetAsync()
    {
        if (string.IsNullOrEmpty(HttpContext.Session.GetString("_LoggedIn")))
        {
            return Redirect("/Index");
        }
        
        IndexList =  await Context.Consultants
            .AsNoTracking()
            .Include(c => c.Projects)
                .ThenInclude(p=>p.Status)
            .Include(c => c.Skills)
                .ToListAsync();
        return Page();
    }
}

UI/Pages/Projects/Create.cshtml.cs
using DB;
using DB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace UI.Pages.Projects;

public class CreateModel : PageModel
{
    private ProjectContext Context { get; set; }
    [BindProperty] public Project Project { get; set; }
    public SelectList StatusSelect { get; set; }
    public SelectList CompanySelect { get; set; }
    public CreateModel(ProjectContext context)
    {
        Context = context;
    }
    
    public IActionResult OnGet()
    {
        CompanySelect = new SelectList(Context.Companies, "Id", "Name");
        StatusSelect = new SelectList(Context.Statuses, "Id", "Name");
        return Page();
    }

    public IActionResult OnPost()
    {
        if (string.IsNullOrEmpty(HttpContext.Session.GetString("_LoggedIn")))
        {
            return Redirect("/Index");
        }
        if (!ModelState.IsValid)
        {
            return Redirect("/Projects/Create");
        }

        Context.Projects.Add(Project);
        Context.SaveChanges();
        return Redirect("/Projects/Index");
    }
}

UI/Pages/Skills.cshtml.cs
using System.Linq;
using System.Text.Json.Serialization;
using DB;
using DB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace UI.Pages;

public class Skills : PageModel
{
    private ProjectContext Context { get; set; }
    
    [BindProperty] public int SkillId { get; set; }
    [BindProperty] public string SkillInput { get; set; }
    [BindProperty ]public string entitytype { get; set; }
    [BindProperty] public Consultant ListConsultant { get; set; }
    [BindProperty] public Project ListProject { get; set; }

    public Skills(ProjectContext context)
    {
        Context = context;
    }
    
    public IActionResult OnGet()
    {
        return Redirect("/Index");
    }

    public IActionResult OnPostSkillSelect()
    {
        Skill selected;
        switch (entitytype)
        {
            case "consultant":
                Consultant dbConsultant = Context.Consultants
                    .Include(c=>c.Skills)
                    .Single(c => c.Id == ListConsultant.Id);
                selected = Context.Skills.Single(s => s.Id == SkillId);
                dbConsultant.Skills.Add(selected);
                Context.Update(dbConsultant);
                Context.SaveChanges();
                return RedirectToPage("/Consultants/Edit",new{id=dbConsultant.Id});
            case "project":
                Project dbProject = Context.Projects
                    .Include(p => p.Skills)
                    .Single(p => p.Id == ListProject.Id);
                selected = Context.Skills.Single(s => s.Id == SkillId);
                dbProject.Skills.Add(selected);
                Context.Update(dbProject);
                Context.SaveChanges();
                return RedirectToPage("/Projects/Skills",new{id=dbProject.Id});
        }
        return RedirectToPage("/Index");
    }

    public IActionResult OnPostSkillInput()
    {
        Skill selected;
        switch (entitytype)
        {
            case "consultant":
                Consultant dbConsultant = Context.Consultants
                    .Include(c=>c.Skills)
                    .Single(c => c.Id == ListConsultant.Id);
                selected = Context.Skills.SingleOrDefault(s=>s.Name==SkillInput);
                if (null == selected)
                {
                    selected = new(){
                        Name = SkillInput
                    };
                }
                dbConsultant.Skills.Add(selected);
                Context.Update(dbConsultant);
                Context.SaveChanges();
                return RedirectToPage("/Consultants/Edit",new{id=dbConsultant.Id});
            case "project":
                Project dbProject = Context.Projects
                    .Include(p => p.Skills)
                    .Single(p => p.Id == ListProject.Id);
                selected = Context.Skills.SingleOrDefault(s=>s.Name==SkillInput);
            {
                selected = new(){
                    Name = SkillInput
                };
            }
                dbProject.Skills.Add(selected);
                Context.Update(dbProject);
                Context.SaveChanges();
                return RedirectToPage("/Projects/Skills",new{id=dbProject.Id});
        }
        return Redirect("/Index");
    }

    public IActionResult OnGetRemove(int? id, int? SkillId, string entitytype)
    {
        switch (entitytype)
        {
            case "consultant":
                Consultant dbConsultant = Context.Consultants
                    .Include(c=>c.Skills)
                    .Single(c => c.Id == id);
                Skill selected = Context.Skills.Single(s => s.Id == SkillId);
                dbConsultant.Skills.Remove(selected);
                Context.Update(dbConsultant);
                Context.SaveChanges();
                return RedirectToPage("/Consultants/Edit",new{ id = dbConsultant.Id});
            case "project":
                Project dbProject = Context.Projects
                    .Include(p => p.Skills)
                    .Single(p => p.Id == id);
                selected = Context.Skills.Single(s => s.Id == SkillId);
                dbProject.Skills.Remove(selected);
                Context.Update(dbProject);
                Context.SaveChanges();
                return RedirectToPage("/Projects/Skills",new{ id = dbProject.Id});
        }
        return Redirect("/Index");
    }
}

UI/Pages/Consultants/Connect.cshtml
@page
@model UI.Pages.Consultants.ConnectModel
@{
    Layout = "_Admin";
}
<h2>Consultants for @Model.PageProject.Name</h2>
<div class="row">
        <div class="col">
            <h3>Consults in project:</h3>
            <ol>
                @foreach (var consult in @Model.PageProject.Consultants)
                {
                    <li>@consult.FullName</li>
                }
            </ol>
        </div>
    <div class="col">
        <h3>Add New Consult:</h3>
        <div class="form-group">
            <form asp-page-handler="Add" method="post">
                <input type="hidden" asp-for="PageProject.Id"/>
                <label asp-for="ListConsult.Id" class="control-label">Konsulter: </label>
                <select asp-for="ListConsult.Id" class="form-control" asp-items="@Model.AddSelect">
                </select>
                <span asp-validation-for="ListConsult.Id" class="text-danger"/>
                <button class="btn btn-default">Add</button>
            </form>
            <form asp-page-handler="Remove" method="post">
                <input type="hidden" asp-for="PageProject.Id"/>
                <label asp-for="ListConsult.Id" class="control-label">Konsulter: </label>
                <select asp-for="ListConsult.Id" class="form-control" asp-items="@Model.RemoveSelect">
                </select>
                <span asp-validation-for="ListConsult.Id" class="text-danger"/>
                <button class="btn btn-default">Remove</button>
            </form>
        </div>
    </div>
</div>

UI/Pages/Consultants/Create.cshtml
@page
@model UI.Pages.Consultants.Create

@{
    Layout = "_Admin";
}
<h1>Create</h1>

<h4>Consultant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Consult.FirstName" class="control-label">First Name</label>
                <input type="text" asp-for="Consult.FirstName" class="form-control">
                <span asp-validation-for="Consult.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Consult.LastName" class="control-label">Last Name</label>
                <input type="text" asp-for="Consult.LastName" class="form-control">
                <span asp-validation-for="Consult.LastName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

UI/Pages/Consultants/Delete.cshtml
@page
@model UI.Pages.Consultants.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "_Admin";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Consultant</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Consultant.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Consultant.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Consultant.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Consultant.LastName)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Consultant.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

UI/Pages/Consultants/Edit.cshtml
@page
@using DB.Models
@model UI.Pages.Consultants.EditModel
@{
    Layout = "_Admin";
}
<h4>Edit Consult:</h4>
<hr/>

<div class="row">
    <div class="col">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ListConsultant.Id"/>
            <div class="form-group">
                <label asp-for="ListConsultant.FirstName" class="control-label"></label>
                <input type="text" asp-for="ListConsultant.FirstName" value="@Model.ListConsultant.FirstName" class="form-control"/>
                <span asp-validation-for="ListConsultant.FirstName" class="text-danger"/>
            </div>
            <div class="form-group">
                <label asp-for="ListConsultant.LastName" class="control-label"></label>
                <input type="text" asp-for="ListConsultant.LastName" value="@Model.ListConsultant.LastName" class="form-control"/>
                <span asp-validation-for="ListConsultant.LastName" class="text-danger"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Save Edit" class="btn btn-light btn-outline-dark mt-2"/>
            </div>
        </form>
        <hr/>
        <form method="post">
            @{
                bool disabled = @Model.SkillSelect.Count() > 0 ? false : true;
            }
            <input type="hidden" name="entitytype" value="consultant"/>
            <input type="hidden" asp-for="ListConsultant.Id"/>
            <div class="form-group mb-3">
                <label asp-for="SkillId" class="control-label">Add existing skill:</label>
                <select disabled="@disabled" asp-for="SkillId" class="form-control" asp-items="@Model.SkillSelect"></select>
                <span asp-validation-for="SkillId" class="text-danger"/>
                <button disabled="@disabled" asp-page="/Skills" asp-page-handler="SkillSelect" type="submit" class="btn btn-light btn-outline-dark mt-2">Add Existing</button>
            </div>
            <div class="form-group">
                <label asp-for="SkillInput" class="control-label">Add new skill:</label>
                <input type="text" asp-for="SkillInput" class="form-control"/>
                <span asp-validation-for="SkillInput" class="text-danger"/>
                <button asp-page="/Skills" asp-page-handler="SkillInput" type="submit" class="btn btn-light btn-outline-dark mt-2">Add New</button>
            </div>
        </form>
        
        <a asp-page="/Consultants/Delete" asp-route-id="@Model.ListConsultant.Id" class="btn btn-danger">Delete</a>
    </div>
    <div class="col">
        <table class="table table-striped m-auto w-50">
            <thead>
            <tr>
                <th colspan="3" class="col text-center">Skills</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var skill in @Model.ListConsultant.Skills.OrderBy(s => s.Name))
            {
                <tr>
                    <td>
                        @skill.Name
                    </td>
                    <td class="col-1">
                        <a asp-page="/Skills" asp-route-SkillId="@skill.Id" asp-route-id="@Model.ListConsultant.Id" asp-route-entitytype="consultant" asp-page-handler="Remove" type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" style="color:red;" viewBox="0 0 16 16">
                                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                            </svg>
                        </a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

UI/Pages/Consultants/Index.cshtml
@page
@using Microsoft.EntityFrameworkCore
@model UI.Pages.Consultants.Index
@{
    Layout = "_Admin";
}
<div class="container w-50 mt-4">
    <h1 class="display-2 text-center mb-4">Consultants:</h1>
    @foreach (var c in Model.IndexList)
    {
        <div class="card mb-4">
            <div class="card-header text-center">
                <h3 style="display: inline !important;">@c.FullName</h3>
                <a asp-page="/Consultants/Edit" asp-route-id="@c.Id">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil-square text-black" viewBox="0 0 16 25">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                    </svg>
                </a>
            </div>
            <div class="card-body m-0 p-0">
                <div class="row">
                    <div class="col" style="padding-right:0">
                        <div class="list-group-flush rounded-0">
                            <div class="list-group-item disabled text-center text-black" style="height:2.5em; border-bottom: 2px solid gray;">
                                <p>Skills</p>
                            </div>
                            @foreach (var skill in c.Skills)
                            {
                                <li class="list-group-item"> @skill.Name</li>
                            }
                        </div>
                    </div>
                    <div class="col" style="border-left: 1px solid silver; padding-left:0">
                        <div class="list-group-flush">
                            <div class="list-group-item disabled text-center text-black" style="height:2.5em; border-bottom: 2px solid gray;">
                                <p>Projects</p>
                            </div>
                            @foreach (var project in c.Projects)
                            {
                                <li class="list-group-item"> @project.Name: @project.Status.Name</li>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>